[package]
name = "modern-search-engine"
version = "2.0.0"
edition = "2021"

[dependencies]
# Server and async
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
futures = "0.3"

# Search and indexing
tantivy = "0.19"
rust-bert = "0.20"

# Document processing
lopdf = "0.31"
scraper = "0.17"
base64 = "0.21"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid"] }
postgres = "0.19"

# Utils
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
uuid = { version = "1.4", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
config = "0.13"

# Logging and metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
metrics = "0.20"
metrics-exporter-prometheus = "0.11"

# HTML processing
html2text = "0.4"
ammonia = "3.3"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
wiremock = "0.5"
pretty_assertions = "1.0"